const repository={owner:"RADWAN22s",name:"radwan-sheet",branch:"main",path:"app.js"};
let plannerData=/* PLANNER_DATA_START */{
  "life":[
    {"icon":"✦","title":"Today","key":"today","text":"One clear focus, a little breathing room, and the next kind thing to do."},
    {"icon":"↗","title":"Goals","key":"goals","text":"Big intentions for creative work, learning, money, and the year ahead."},
    {"icon":"⌁","title":"Habits","key":"habits","text":"Small routines that make the days calmer, healthier, and more consistent."},
    {"icon":"♡","title":"Family & Friends","key":"family","text":"People to call, check in on, celebrate, and make time for."},
    {"icon":"+","title":"Health","key":"health","text":"Movement, rest, appointments, and the basics that keep energy steady."},
    {"icon":"⌖","title":"Travel","key":"travel","text":"Places to go, details to remember, and trips that deserve a little space."},
    {"icon":"☆","title":"Wishlist","key":"wishlist","text":"Things to try, buy, learn, visit, or simply keep dreaming about."},
    {"icon":"☼","title":"Open space","key":"open","text":"Future additions can live here as the planner grows with real life."}
  ],
  "quickNotes":"",
  "days":[
    {"date":"2026-09-07","outside":true,"events":[],"note":""},{"date":"2026-09-08","outside":true,"events":[],"note":""},{"date":"2026-09-09","outside":true,"events":[],"note":""},{"date":"2026-09-10","outside":true,"events":[],"note":""},{"date":"2026-09-11","today":true,"events":[],"note":"Open / add later"},{"date":"2026-09-12","events":[{"text":"Morning shoot","tone":"accent"},{"text":"Return equipment to Taleen","tone":"accent"},{"text":"Possible shoot with Fouad","tone":"accent"}],"note":""},{"date":"2026-09-13","events":[{"text":"Shoot with Hesham at the hotel where Islam works","tone":"mint"}],"note":""},{"date":"2026-09-14","events":[{"text":"Morning school trip with Ahmed","tone":"yellow"},{"text":"Evening invitation for acting with Hesham","tone":"yellow"}],"note":""},{"date":"2026-09-15","events":[{"text":"Aunt traveling in the morning","tone":"lavender"}],"note":""},
    {"date":"2026-09-16","events":[],"note":"Open / add later"},{"date":"2026-09-17","events":[],"note":"Open / add later"},{"date":"2026-09-18","events":[],"note":"Open / add later"},{"date":"2026-09-19","events":[],"note":"Open / add later"},{"date":"2026-09-20","events":[],"note":"Open / add later"},{"date":"2026-09-21","events":[],"note":"Open / add later"},{"date":"2026-09-22","events":[],"note":"Open / add later"},{"date":"2026-09-23","events":[],"note":"Open / add later"},{"date":"2026-09-24","events":[],"note":"Open / add later"},{"date":"2026-09-25","events":[],"note":"Open / add later"},{"date":"2026-09-26","events":[],"note":"Open / add later"},{"date":"2026-09-27","events":[],"note":"Open / add later"},{"date":"2026-09-28","events":[],"note":"Open / add later"},{"date":"2026-09-29","events":[],"note":"Open / add later"},{"date":"2026-09-30","events":[],"note":"Open / add later"},{"date":"2026-10-01","events":[],"note":"Open / add later"},{"date":"2026-10-02","events":[],"note":"Open / add later"},{"date":"2026-10-03","events":[],"note":"Open / add later"},{"date":"2026-10-04","events":[],"note":"Open / add later"},{"date":"2026-10-05","events":[],"note":"Open / add later"},{"date":"2026-10-06","events":[],"note":"Open / add later"},{"date":"2026-10-07","events":[],"note":"Open / add later"},{"date":"2026-10-08","events":[],"note":"Open / add later"},{"date":"2026-10-09","events":[],"note":"Open / add later"},{"date":"2026-10-10","events":[],"note":"Open / add later"},{"date":"2026-10-11","outside":true,"events":[],"note":""}
  ]
} /* PLANNER_DATA_END */;

const $=id=>document.getElementById(id);let editing=false,saving=false;
const weekdays=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"];
function status(text,state=""){const el=$("save-status");el.textContent=text;if(state)el.dataset.state=state;else delete el.dataset.state}
function renderLife(){const grid=$("life-grid");grid.replaceChildren();plannerData.life.forEach(item=>{const card=document.createElement("article");card.className="life-card";card.innerHTML=`<div class="life-icon">${item.icon}</div><h3>${item.title}</h3>`;const text=document.createElement("p");text.dataset.lifeKey=item.key;text.contentEditable=editing;text.textContent=item.text;card.append(text);grid.append(card)})}
function number(date){return Number(date.slice(8,10))}function month(date){return date.slice(5,7)==="10"?"Oct":""}
function renderCalendar(){const calendar=$("calendar");calendar.replaceChildren();weekdays.forEach(day=>{const el=document.createElement("div");el.className="weekday";el.textContent=day;calendar.append(el)});plannerData.days.forEach(day=>{const cell=document.createElement("div");cell.className="calendar-day";cell.dataset.date=day.date;if(day.outside)cell.classList.add("outside");if(day.today)cell.classList.add("today");const date=document.createElement("div");date.className="date-number";date.append(String(number(day.date)));if(month(day.date)){const m=document.createElement("span");m.className="calendar-range";m.textContent=month(day.date);date.append(m)}if(day.today){const t=document.createElement("span");t.className="today-badge";t.textContent="Today";date.append(t)}cell.append(date);day.events.forEach((event,index)=>{const item=document.createElement("div");item.className=`calendar-event ${event.tone||"accent"}`;item.dataset.kind="event";item.dataset.index=index;item.contentEditable=editing;item.textContent=event.text;cell.append(item)});if(!day.outside&&(!day.events.length||day.note)){const note=document.createElement("div");note.className="open-note";note.dataset.kind="note";note.contentEditable=editing;note.dataset.placeholder="Click to add a note";note.textContent=editing?day.note:(day.note||"Open / add later");cell.append(note)}if(!day.outside){const add=document.createElement("button");add.className="calendar-add";add.type="button";add.textContent="+ Add event";add.addEventListener("click",()=>{sync();day.events.push({text:"",tone:"accent"});day.note="";renderCalendar();const target=calendar.querySelector(`[data-date="${day.date}"] [data-kind="event"]:last-of-type`);if(target)target.focus()});cell.append(add)}calendar.append(cell)})}
function sync(){plannerData.life.forEach(item=>{const el=document.querySelector(`[data-life-key="${item.key}"]`);if(el)item.text=el.innerText.trim()});plannerData.quickNotes=$("quick-notes").innerText.trim();plannerData.days.forEach(day=>{const cell=document.querySelector(`[data-date="${day.date}"]`);if(!cell||day.outside)return;day.events=[...cell.querySelectorAll('[data-kind="event"]')].map(el=>({text:el.innerText.trim(),tone:el.className.replace("calendar-event","").trim()||"accent"})).filter(event=>event.text);const note=cell.querySelector('[data-kind="note"]');day.note=note?note.innerText.trim():""})}
function setEditing(value){editing=value;document.body.classList.toggle("edit-mode",value);$("start-edit").hidden=value;$("cancel-edit").hidden=!value;$("save-edit").hidden=!value;$("quick-notes").contentEditable=value;renderLife();renderCalendar()}
function openAuth(){$("auth-error").hidden=true;$("auth-error").textContent="";$("github-token").value="";$("auth-modal").hidden=false;setTimeout(()=>$("github-token").focus(),0)}function closeAuth(){if(!saving){$("auth-modal").hidden=true;$("github-token").value=""}}
function b64encode(value){const bytes=new TextEncoder().encode(value);let bin="";bytes.forEach(byte=>bin+=String.fromCharCode(byte));return btoa(bin)}function b64decode(value){const bin=atob(value.replace(/\s/g,""));return new TextDecoder().decode(Uint8Array.from(bin,c=>c.charCodeAt(0)))}
function updateSource(source){const startMarker="/* PLANNER_DATA_START */",endMarker="/* PLANNER_DATA_END */",start=source.indexOf(startMarker),end=source.indexOf(endMarker,start+startMarker.length);if(start<0||end<0)throw new Error("Planner data block was not found in app.js.");return source.slice(0,start+startMarker.length)+"\n"+JSON.stringify(plannerData,null,2)+"\n"+source.slice(end)}
async function request(url,options){const response=await fetch(url,options),body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.message||`GitHub returned ${response.status}.`);return body}
async function save(){if(saving)return;const token=$("github-token").value.trim();if(!token){$("auth-error").hidden=false;$("auth-error").textContent="Paste a GitHub token to continue.";return}sync();saving=true;$("confirm-save").disabled=true;$("save-edit").disabled=true;status("Saving to GitHub…");const headers={Accept:"application/vnd.github+json",Authorization:`Bearer ${token}`,"X-GitHub-Api-Version":"2022-11-28"},url=`https://api.github.com/repos/${repository.owner}/${repository.name}/contents/${repository.path}`;try{const current=await request(`${url}?ref=${repository.branch}`,{headers}),source=updateSource(b64decode(current.content));await request(url,{method:"PUT",headers:{...headers,"Content-Type":"application/json"},body:JSON.stringify({message:"Update planner data",content:b64encode(source),sha:current.sha,branch:repository.branch})});$("auth-modal").hidden=true;$("github-token").value="";setEditing(false);status("Saved to GitHub. GitHub Pages may take a minute to refresh.","success")}catch(error){$("auth-error").hidden=false;$("auth-error").textContent=error.message;status("Save failed. Check the token permission and try again.","error")}finally{saving=false;$("confirm-save").disabled=false;$("save-edit").disabled=false}}
$("start-edit").addEventListener("click",()=>{setEditing(true);status("Edit mode is on. Click any highlighted field to change it.")});$("cancel-edit").addEventListener("click",()=>{location.reload()});$("save-edit").addEventListener("click",openAuth);$("confirm-save").addEventListener("click",save);$("close-auth").addEventListener("click",closeAuth);$("cancel-auth").addEventListener("click",closeAuth);$("auth-modal [data-close-auth]").addEventListener("click",closeAuth);$("github-token").addEventListener("keydown",event=>{if(event.key==="Enter")save();if(event.key==="Escape")closeAuth()});$("quick-notes").textContent=plannerData.quickNotes;renderLife();renderCalendar();
